IMAGE_FORMATS = ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff', '.webp', '.heic']
VIDEO_FORMATS = ['.mp4', '.avi', '.mov', '.mkv', '.m4v']
SUPPORTED_MEDIA_FORMATS = IMAGE_FORMATS + VIDEO_FORMATS

# State mapping (Full name to abbreviation)
STATE_MAPPING = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

# Country mapping (Various names to standard English name)
COUNTRY_MAPPING = {
    # English variations
    'United States of America': 'United States',
    'USA': 'United States',
    'U.S.A.': 'United States',
    'America': 'United States',
    'UK': 'United Kingdom',
    'Great Britain': 'United Kingdom',
    
    # Arabic names
    'المملكة العربية السعودية': 'Saudi Arabia',
    'مصر': 'Egypt',
    'الإمارات العربية المتحدة': 'United Arab Emirates',
    'قطر': 'Qatar',
    'الكويت': 'Kuwait',
    'البحرين': 'Bahrain',
    'عمان': 'Oman',
    'العراق': 'Iraq',
    'سورية': 'Syria',
    'الأردن': 'Jordan',
    'لبنان': 'Lebanon',
    'فلسطين': 'Palestine',
    'اليمن': 'Yemen',
    'المغرب': 'Morocco',
    'تونس': 'Tunisia',
    'الجزائر': 'Algeria',
    'ليبيا': 'Libya',
    'السودان': 'Sudan',
    
    # Asian names
    '中国': 'China',
    'भारत': 'India',
    'പാکിസ്താന്': 'Pakistan',
    'পাকিস্তান': 'Pakistan',
    'پاکستان': 'Pakistan',
    '日本': 'Japan',
    '한국': 'South Korea',
    '대한민국': 'South Korea',
    'ประเทศไทย': 'Thailand',
    'Việt Nam': 'Vietnam',
    'မြန်မာ': 'Myanmar',
    'இலங்கை': 'Sri Lanka',
    'ශ්‍රී ලංකා': 'Sri Lanka',
    'नेपाल': 'Nepal',
    
    # European variations
    'Deutschland': 'Germany',
    'España': 'Spain',
    'Italia': 'Italy',
    'Frankrijk': 'France',
    'Россия': 'Russia',
    'Polska': 'Poland',
    'Sverige': 'Sweden',
    'Norge': 'Norway',
    'Danmark': 'Denmark',
    'Suomi': 'Finland',
    'Nederland': 'Netherlands',
    'Ελλάδα': 'Greece',
    'Česko': 'Czech Republic',
    'Österreich': 'Austria',
    'Schweiz': 'Switzerland',
    'België': 'Belgium',
    'Magyarország': 'Hungary',
    'Portugal': 'Portugal',
    
    # Latin American variations
    'México': 'Mexico',
    'Brasil': 'Brazil',
    'Argentina': 'Argentina',
    'Perú': 'Peru',
    'Colombia': 'Colombia',
    'Venezuela': 'Venezuela',
    'Chile': 'Chile'
}

# Country codes (Full name to abbreviation)
COUNTRY_CODES = {
    'United States': 'US',
    'United Kingdom': 'GB',
    'Canada': 'CA',
    'Australia': 'AU',
    'Germany': 'DE',
    'France': 'FR',
    'Italy': 'IT',
    'Spain': 'ES',
    'Portugal': 'PT',
    'Ireland': 'IE',
    'Netherlands': 'NL',
    'Belgium': 'BE',
    'Switzerland': 'CH',
    'Austria': 'AT',
    'Sweden': 'SE',
    'Norway': 'NO',
    'Denmark': 'DK',
    'Finland': 'FI',
    'Iceland': 'IS',
    'Russia': 'RU',
    'Poland': 'PL',
    'Ukraine': 'UA',
    'Greece': 'GR',
    'Turkey': 'TR',
    'China': 'CN',
    'Japan': 'JP',
    'South Korea': 'KR',
    'North Korea': 'KP',
    'India': 'IN',
    'Pakistan': 'PK',
    'Bangladesh': 'BD',
    'Thailand': 'TH',
    'Vietnam': 'VN',
    'Indonesia': 'ID',
    'Philippines': 'PH',
    'Malaysia': 'MY',
    'Singapore': 'SG',
    'Saudi Arabia': 'SA',
    'United Arab Emirates': 'AE',
    'Israel': 'IL',
    'Egypt': 'EG',
    'South Africa': 'ZA',
    'Nigeria': 'NG',
    'Kenya': 'KE',
    'Morocco': 'MA',
    'Brazil': 'BR',
    'Argentina': 'AR',
    'Mexico': 'MX',
    'Colombia': 'CO',
    'Peru': 'PE',
    'Chile': 'CL',
    'New Zealand': 'NZ'
}